version: '3.1'

services:
  mariadb:
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_PASSWORD: qwe123
      MARIADB_DATABASE: recordings
      MARIADB_USER: admin
      MARIADB_PASSWORD: qwerty
      MARIADB_ROOT_HOST: '%'
    volumes:
      - "./create-tables.sql:/root/create-tables.sql:Z"
      - "./mysql:/var/lib/mysql:Z"
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
